---
- name: Stop apps
  ansible.builtin.import_tasks:
    file: tag_stop.yml

- name: Docker Setup & Baseline
  include_role: 
    name: murphywants-ansible-role-component-docker
  tags: setup

- name: Install sqlite3 # For backups
  ansible.builtin.package:
    name: sqlite3