---
  - name: Create vaultwarden ZFS volume
    community.general.zfs:
      name: "{{ VAULTWARDEN_STORAGE_ZFS_POOL }}/{{ VAULTWARDEN_STORAGE_ZFS_FS }}"
      state: present
      extra_zfs_properties:
        mountpoint: "{{ VAULTWARDEN_PATH }}"

  - name: Create folders
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
    loop:
      - "{{ VAULTWARDEN_PATH }}"
      - "{{ VAULTWARDEN_PATH }}/volumes"
      - "{{ VAULTWARDEN_PATH }}/volumes/data"
      - "{{ VAULTWARDEN_PATH }}/backups"
      - "{{ VAULTWARDEN_PATH }}/backups/logs"
      - "{{ VAULTWARDEN_PATH }}/scripts"
      - "{{ VAULTWARDEN_PATH }}/docs"

  - name: Copy docker compose file
    ansible.builtin.template:
      src: "{{ role_path }}/templates/vaultwarden_docker-compose.yml.j2"
      dest: "{{ VAULTWARDEN_PATH }}/docs/docker-compose.yml"

  - name: Copy backup script
    ansible.builtin.template:
      src: "{{ role_path }}/templates/vaultwarden_backup.sh.j2"
      dest: "{{ VAULTWARDEN_PATH }}/scripts/vaultwarden_backup.sh"
      mode: "0700"
