---
  - name: Check if docker-compose file exists
    ansible.builtin.stat:
      path: "{{ VAULTWARDEN_PATH }}/docs/docker-compose.yml"
    register: vaultwarden_stat_docker_compose_file

  - name: Docker Compose Start Apps
    community.docker.docker_compose_v2:
      project_src: "{{ VAULTWARDEN_PATH }}/docs"
      files: "docker-compose.yml"
      state: present
      pull: always
      project_name: vaultwarden
    when: vaultwarden_stat_docker_compose_file.stat.exists
    
  - name: Create cronjob to run database dump script daily at 10pm
    ansible.builtin.cron:
      backup: true
      hour: 20
      minute: 4
      job: "bash {{ VAULTWARDEN_PATH }}/scripts/vaultwarden_backup.sh -n 30"
      name: "Vaultwarden - Backup"
      state: "present"