---
  - name: Stop apps
    ansible.builtin.import_tasks:
      file: tag_stop.yml

  - name: Backup apps
    ansible.builtin.import_tasks:
      file: tag_backup.yml

  - name: Start apps # Docker will pull on start
    ansible.builtin.import_tasks:
      file: tag_start.yml
